services:
  storefront:
    build:
      context: https://github.com/fazil-amir/storefront-nextjs.git#main
      dockerfile: Dockerfile
    image: storefront:latest
    container_name: storefront
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production